name: item_radar
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  flutter_bloc: ^9.1.0
  google_maps_flutter: ^2.2.3
  url_launcher: ^6.1.14
  image_picker: ^1.0.7
  fluttertoast: ^8.2.12
  intl: ^0.18.0
  share_plus: ^7.2.1
  firebase_storage: ^12.4.5
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  provider: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
